language: node_js

node_js:
  - node

branches:
  only:
    - master
    - /^deploy-.*$/

cache:
  yarn: true
  directories:
    - ~/.npm
    - .jest

before_script:
  - npm install -g expo-cli
  - yarn install

script:
  - yarn test --ci
  - expo login -u $EXPO_CLI_USERNAME -p $EXPO_CLI_PASSWORD
  - expo publish --non-interactive
