language: node_js

node_js:
  - node
  - lts/*

branches:
  only:
    - master
    - /^deploy-.*$/

cache:
  directories:
    - ~/.npm

before_script:
  - npm install -g npm@latest

script:
  - npm ci
  - npx jest --ci
