language: node_js

node_js:
  - node

branches:
  only:
    - master
    - /^deploy-.*$/

cache:
  yarn: true
  directories:
    - ~/.npm
    - .jest

stages:
  - test
  - publish

before_script:
  - npm install -g expo-cli
  - yarn install

jobs:
  include:
    - stage: test
      script:
        - yarn test --ci
    - stage: publish
      script:
        - expo login -u $EXPO_CLI_USERNAME -p $EXPO_CLI_PASSWORD
        - expo publish --non-interactive
