language: node_js

node_js:
  - node

branches:
  only:
    - master
    - /^deploy-.*$/

cache:
  yarn: true
  directories:
    - ~/.npm
    - .jest

stages:
  - name: test
  - name: publish
    # require the branch name to be uat (note for PRs this is the base branch name)
    if: branch = uat
  - name: deploy
    # require the branch name to be master (note for PRs this is the base branch name)
    if: branch = master

before_script:
  - npm install -g expo-cli
  - yarn install

jobs:
  include:
    - stage: test
      script:
        - yarn test --ci
    - stage: publish
      script:
        - expo login -u $EXPO_CLI_USERNAME -p $EXPO_CLI_PASSWORD
        - expo publish --non-interactive --release-channel $TRAVIS_COMMIT
    - stage: deploy
      before_script:
        - npm install -g expo-cli
      script:
        - expo login -u $EXPO_CLI_USERNAME -p $EXPO_CLI_PASSWORD
        - expo build:android
